### ISSUE TITLE
Prep for merge into DAppNode Main Repo

### ISSUE THREAD

**Issue by alexpeterson91** [Nabsku/DAppNodePackage-Besu#3]
this isnt fully inclusive of everything but some things that will need to be done are

- [x] #6
- [x] cleanup setup wizard, i see no point in the advanced/basic option should just remove it and put a descriptor in the advanced config editor, most people do not ever go on GH and read the README file where you have described the use of the BESU_OPTS field.
- [x] RPC APIs should just be enabled no need to have that in the startup wizard, may not even need a setup wizard right now, possibly for merge.
- [x] Remove reference to ETH2
- [x] #5
- [x] versioning needs to be semantic versioning.  For dappnode we start with v0.1.0
- [x] #4

**Comment by Nabsku** [comment]
A few things from my side @alexpeterson91:

setup wizard: I've intentionally left the basic configuration as small as possible and selected the most sane defaults for the advanced configuration. I believe that offering the option to easily change settings that might not be interesting for basic usage should still be as easy as possible (and even with guard rails! can't select wrong values, which you can in the advanced editor). 

With all due respect, if we strive to be as user friendly as possible, I think this is the way to go. If the decision is made against it though, I will remove it. 

And people who don't go around on GH probably also won't need to fiddle with the BESU_OPTS env variable :p

P2P Port: Whats the rationale behind the p2p port thing? that should only be an issue with running more than one execution client?  

Semantic versioning: I am using semantic versioning (as can be seen here: https://dappnode.github.io/explorer/#/repo/0x2914045962c6ea7706311d47937be373b71a6060). Whats the rationale behind starting with v0.1.0?

Eth2 references: I can remove the "/Eth2" in the setup-wizard.yml if its needed. I do not use it myself but left it in there as not everyone uses EL/CL terminology.

**Comment by tropicar** [comment]
The port we have assigned for Besu client on mainnet should be 30414, I have added it to the https://github.com/dappnode/DAppNode/issues/457

**Comment by alexpeterson91** [comment]
> **Semantic versioning**: I am using semantic versioning (as can be seen here: https://dappnode.github.io/explorer/#/repo/0x2914045962c6ea7706311d47937be373b71a6060). Whats the rationale behind starting with v0.1.0?

honestly forget that i misread upstream version as package version, but i said v0.1.0 because when developing with the dappnodesdk its default initial version when running `init` is or at least was v0.1.0, most DNPs on dappnode started that way and have moved on using semver  for years now, but ive seen some other packages lately that diverge from this method i think its been changed or at. least it's not nearly as important so long as SemVer is used properly.

**Comment by tropicar** [comment]
Something that has to be done too is to change the name of the package from public to dnp.

**Comment by alexpeterson91** [comment]
> Something that has to be done too is to change the name of the package from public to dnp.

was gonna wait till it was in the dappnode organization for that one.  should we fork this repo like we did for Geth from Nanexcool, or do we have Nabsku transfer it out of his intp the dappnode organization.

**Comment by tropicar** [comment]
I check the package, and change the name of the services, i changed the setup wizard to have it similar to other execution clients. I think is ready.

**Comment by Nabsku** [comment]
well then, I'm going to to archive this repo.
